INSERT INTO public.itinerary (itinerary_source,itinerary_target,trip_id,travel_time,travel_distance,sequencia,note) VALUES
	 ('Santo Tomé (AR)','Porto Alegre',42,480,600,6,''),
	 ('Porto Alegre','Santo Ângelo',42,360,436,1,'Entre Ijuis'),
	 ('Santo Ângelo','Porto Xavier',42,210,247,2,'São Miguel das Missões, São Lourenço das Missões, São Nicolau'),
	 ('Porto Xavier','Posadas (AR)',42,240,242,3,'Ruinas de Santa Maria la Mayor, Guarani Santa Ana, Loreto, San Ignacio, Corpus, Posadas'),
	 ('Posadas (AR)','San Cosme y Damian (PY)',42,420,370,4,'Encarnacion, La Santissima Trinidad, Jssus de Tavarangue, Santa Rosa, Santa Maria, San Ignacio'),
	 ('Porto Alegre, RS','Passo de Torres, SC',46,150,197,1,''),
	 ('Passo de Torres, SC','Imbituba, SC',46,323,314,2,'São João do Sul, Praia Grande, Sombrio, Balneário Gaivota, Araranguá, Balneário Arroio do Silva, Balneário Rincão, Jaguaruna, Tubarão, Laguna'),
	 ('Imbituba, SC','Lages, SC',46,240,278,3,''),
	 ('Lages, SC','Anita Garibaldi, SC',46,257,275,4,'Correia Pinto, Ponte Alta, Curitibanos, São José do Cerrito, Capão Alto, Campo Belo do Sul, Cerro Negro'),
	 ('Anita Garibaldi, SC','Porto Alegre, RS',46,330,355,5,''),
	 ('Porto Alegre','Pelotas',41,323,389,1,'Guaíba, Camaquã, Rio Grande'),
	 ('Definido pelo viajante','',56,0,0,1,NULL),
	 ('Paradas espontâneas','',56,0,0,2,NULL),
	 ('Porto Alegre','Caxias do Sul',40,0,0,NULL,NULL),
	 ('Caxias do Sul','Flores da Cunha',40,0,0,NULL,NULL),
	 ('Flores da Cunha','Antônio Prado',40,0,0,NULL,NULL),
	 ('Antônio Prado','Bento Gonçalves',40,0,0,NULL,NULL),
	 ('Bento Gonçalves','Garibaldi',40,0,0,NULL,NULL),
	 ('Garibaldi','Porto Alegre',40,0,0,NULL,NULL),
	 ('Porto Alegre','São Leopoldo',44,0,0,NULL,NULL),
	 ('São Leopoldo','Novo Hamburgo',44,0,0,NULL,NULL),
	 ('Porto Alegre','Bento Gonçalves',57,0,0,NULL,NULL),
	 ('Bento Gonçalves','Monte Belo do Sul',57,0,0,NULL,NULL),
	 ('Monte Belo do Sul','Santa Tereza',57,0,0,NULL,NULL),
	 ('Santa Tereza','Porto Alegre',57,0,0,NULL,NULL),
	 ('Porto Alegre','Caxias do Sul',58,0,0,NULL,NULL),
	 ('Caxias do Sul','Farroupilha',58,0,0,NULL,NULL),
	 ('Farroupilha','Bento Gonçalves',58,0,0,NULL,NULL),
	 ('Bento Gonçalves','Porto Alegre',58,0,0,NULL,NULL),
	 ('Porto Alegre','Criciúma',59,0,0,NULL,NULL),
	 ('Criciúma','Porto Alegre',59,0,0,NULL,NULL),
	 ('Novo Hamburgo','Ivoti',44,0,0,NULL,NULL),
	 ('Porto Alegre','Nova Petrópolis',47,0,0,NULL,NULL),
	 ('Nova Petrópolis','Gramado',47,0,0,NULL,NULL),
	 ('Gramado','Canela',47,0,0,NULL,NULL),
	 ('Canela','São Fransciso de Paula',47,0,0,NULL,NULL),
	 ('São Francisco de Paula','Porto Alegre',47,0,0,NULL,NULL),
	 ('Porto Alegre','Cambará do Sul',48,0,0,NULL,NULL),
	 ('Cambará do Sul','Cânion Itaimbezinho',48,0,0,NULL,NULL),
	 ('Cambará do Sul','Cânion Fortaleza',48,0,0,NULL,NULL),
	 ('Cambará do Sul','Porto Alegre',48,0,0,NULL,NULL),
	 ('Porto Alegre','Capão da Canoa',49,0,0,NULL,NULL),
	 ('Capão da Canoa','Torres',49,0,0,NULL,NULL),
	 ('Torres','Porto Alegre',49,0,0,NULL,NULL),
	 ('Porto Alegre','Bagé',50,0,0,NULL,NULL),
	 ('Bagé','Aceguá',50,0,0,NULL,NULL),
	 ('Aceguá','Santana do Livramento',50,0,0,NULL,NULL),
	 ('Santana do Livramento','Porto Alegre',50,0,0,NULL,NULL),
	 ('Porto Alegre','Lajeado',51,0,0,NULL,NULL),
	 ('Lajeado','Estrela',51,0,0,NULL,NULL);
INSERT INTO public.itinerary (itinerary_source,itinerary_target,trip_id,travel_time,travel_distance,sequencia,note) VALUES
	 ('Estrela','Teutônia',51,0,0,NULL,NULL),
	 ('Teutônia','Porto Alegre',51,0,0,NULL,NULL),
	 ('Porto Alegre','Bento Gonçalves',52,0,0,NULL,NULL),
	 ('Bento Gonçalves','Monte Belo do Sul',52,0,0,NULL,NULL),
	 ('Monte Belo do Sul','Garibaldi',52,0,0,NULL,NULL),
	 ('Garibaldi','Porto Alegre',52,0,0,NULL,NULL),
	 ('Ivoti','Porto Alegre',44,0,0,NULL,NULL),
	 ('Porto Alegre','Canoas',53,0,0,NULL,NULL),
	 ('Canoas','São Leopoldo',53,0,0,NULL,NULL),
	 ('São Leopoldo','Porto Alegre',53,0,0,NULL,NULL),
	 ('Porto Alegre','Gramado',54,0,0,NULL,NULL),
	 ('Gramado','Canela',54,0,0,NULL,NULL),
	 ('Canela','São José dos Ausentes',54,0,0,NULL,NULL),
	 ('São José dos Ausentes','Porto Alegre',54,0,0,NULL,NULL),
	 ('Porto Alegre','Cambará do Sul',55,0,0,NULL,NULL),
	 ('Cambará do Sul','Serra do Faxinal',55,0,0,NULL,NULL),
	 ('Serra do Faxinal','Praia Grande (SC)',55,0,0,NULL,NULL),
	 ('Praia Grande (SC)','Porto Alegre',55,0,0,NULL,NULL),
	 ('San Cosme y Damian (PY)','Santo Tomé (AR)',42,240,251,5,'Encarnacion (PY)'),
	 ('Porto Alegre','Santa Maria',45,285,334,1,'O Centro Político e Logístico - Cachoeira do Sul'),
	 ('Santa Maria','Bagé',45,288,303,2,'O Coração do Conflito - São Gabriel'),
	 ('Bagé','Alegrete',45,300,377,3,'Fronteira e Maragatos - Dom Pedrito, Santana do Livramento, Rosário do Sul'),
	 ('Alegrete','Cruz Alta',45,453,583,4,'A Fronteira Oeste - Uruguaiana, São Borja'),
	 ('Cruz Alta','Porto Alegre',45,285,346,5,''),
	 ('Retornos alternativos','',56,0,0,3,NULL),
	 ('Pelotas','Caçapava do Sul',41,252,249,2,'Piratini'),
	 ('Caçapava do Sul','Bagé',41,431,564,3,'Rosário do Sul, Alegrete'),
	 ('Bagé','Porto Alegre',41,340,450,4,'São Lourenço do Sul');
